### ISSUE TITLE
Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery

### ISSUE THREAD

**Issue by gabrieldelaparra** [gabrieldelaparra/Ordos#42]
```bash
Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
app_1  |       An exception was thrown while deserializing the token.
app_1  | Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {53c9f5fa-21c1-4c93-b140-af894c61c6ec} was not found in the key ring.
app_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
app_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
app_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
app_1  |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
app_1  |    --- End of inner exception stack trace ---
app_1  |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
app_1  |    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

**Comment by gabrieldelaparra** [comment]
No reproducible.
