### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'iec61850'

### ISSUE THREAD

**Issue by gabrieldelaparra** [gabrieldelaparra/Ordos#5]
Project IEC61850.NetCore is supposed to copy the iec61850 to the output, the debug machine is throwing an DLLNotFoundException.

Exception Thrown:
```
System.DllNotFoundException: Unable to load DLL 'iec61850': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at IEC61850.Client.IedConnection.IedConnection_create()
   at IEC61850.Client.IedConnection..ctor() in ~\Ordos\IEC61850.NetCore\IEC61850ClientAPI.cs:line 410
   at Ordos.IEDService.Services.MMSService.TestConnection(Device device) in ~\Ordos\Ordos.IEDService\Services\MMSService.cs:line 21
   at Ordos.IEDService.Services.MMSService.GetComtrades() in ~\Ordos\Ordos.IEDService\Services\MMSService.cs:line 50
```

**Comment by gabrieldelaparra** [comment]
After comparing dependencies via [DependencyWalker](http://www.dependencywalker.com/), it seems that both VCRUNTIME140D.DLL and UCRTBASED.DLL are missing in the test environment.

According to some posts, It should have been corrected after installing the [Microsoft Visual C++ 2015 Redistributable Update 3 RC](https://www.microsoft.com/en-us/download/details.aspx?id=52685) but it was not the case. 

Still, I haven't been able to solve this.

**Comment by gabrieldelaparra** [comment]
One of the solutions, was to copy the missing DLLs to the project. I agree with the post author (I don't have the link, I discarded the solution on the spot, still it is the only solution that actually worked)

This is not a really good solution, since new changes to the VC++ Runtime might change, still it is for now a suitable solution.
